### ISSUE TITLE
Saving to a directory

### ISSUE THREAD

**Issue by DevX-Cipher** [cg10036/Themida-Unpacker-for-.NET#2]
hi i was wondering if this can save the files once upacked to a directory as i dont see the code for it to save in current directory

**Comment by cg10036** [comment]
.exe will dump, and you can see source with dnspy or etc.

**Comment by DevX-Cipher** [comment]
is the source code P available at all

**Comment by cg10036** [comment]
What do you mean?

**Comment by cg10036** [comment]
If you can't find dumped exe, #3 this will help.

**Comment by DevX-Cipher** [comment]
the PD.exe is the source code available for this or no

**Comment by cg10036** [comment]
https://github.com/glmcdona/Process-Dump

**Comment by DevX-Cipher** [comment]
ok cheers

**Comment by DevX-Cipher** [comment]
i merged clrjit.dll into the res file so no need of installing net framework stuff

**Comment by cg10036** [comment]
Thank you for your interest in this project. However, it is difficult to update a project that is about 3 years old. In addition, even if this project works without the .NET Framework, it must eventually be installed because it also requires the execution of the program to dump.

**Comment by DevX-Cipher** [comment]
yer i aready tested and changed the code

**Comment by DevX-Cipher** [comment]
hey can we add both into one application instead of running different modules please this is just dumper
